<a href="https://colab.research.google.com/github/amrita-sarkar1/Python-codes/blob/main/Numpyroll.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing library
import numpy as np

$numpy.roll$

***Syntax:***

$numpy.roll(a, shift, axis=None)$

***Note:***
- Roll array elements along a given axis.

- Elements that roll beyond the last position are re-introduced at the first.

***Parameters***

$a$: *array_like*

Input array.

$shift$: int or tuple of ints

The number of places by which elements are shifted. If a tuple, then axis must be a tuple of the same size, and each of the given axes is shifted by the corresponding number. If an int while axis is a tuple of ints, then the same value is used for all given axes.

$axis$: int or tuple of ints, optional

Axis or axes along which elements are shifted. By default, the array is flattened before shifting, after which the original shape is restored.

***Returns:***

$res$: ndarray

Output array, with the same shape as a.




In [2]:
# Defining the array
x = np.arange(10)

# Visualizing the array
print("Original Array: \n",x)
print("\n")

# Applying np.roll
y = np.roll(x, 2)

# Print the result
print("Modified Array: \n",y)

Original Array: 
 [0 1 2 3 4 5 6 7 8 9]


Modified Array: 
 [8 9 0 1 2 3 4 5 6 7]


*The position of each element is shifted by 2.*

In [3]:
# Defining the array
x2 = np.reshape(x, (2, 5))

# Visualizing the array
print("Original Array: \n",x2)
print("\n")

# Applying np.roll
y2 = np.roll(x2, -1, axis=0)

# Print the result
print("Modified Array: \n",y2)

Original Array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


Modified Array: 
 [[5 6 7 8 9]
 [0 1 2 3 4]]


*The elements of the second row are transported to the first row as $shift = -1$*